site_name: MSA SDK - Documentation

docs_dir: docs/sources


# Repository
repo_name: U2D_MSA_SDK
repo_url: https://github.com/swelcker/U2D_MSA_SDK.git
edit_uri: ""

# Copyright
copyright: Stefan Welcker, 2022, stefan@u2d.ai


plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - autorefs
  - section-index
  - mkdocstrings:
      watch:
        - u2d_msa_sdk
      default_handler: python
      handlers:
        python:
          paths: [u2d_msa_sdk]
          options:
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: 'material'
  custom_dir: 'docs'
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: '../images/msa_logo_big.png'
  favicon: '../images/favicon.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:
  - Home: index.md
  - Sites:
    - Admin: admin/admin.md
    - Auth Admin: auth/auth.md
  - Code Reference: reference/
